packages:
  - "."
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@prisma/engines': true
  better-sqlite3: true
  core-js: true
  electron-winstaller: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
# ----------------------
# pnpm clean --lockfile
# collapsing option is: pnpm store prune ; don't use it until needed!
# pnpm install
# check how to change pkgs with: .pnpmfile.mjs at: https://pnpm.io/pnpmfile
# ----------------------
minimumReleaseAgeExclude:
  - mongoose@9.7.0
  - '@takumi-rs/core-darwin-arm64@1.8.0'
  - '@takumi-rs/core-darwin-x64@1.8.0'
  - '@takumi-rs/core-linux-arm64-gnu@1.8.0'
  - '@takumi-rs/core-linux-arm64-musl@1.8.0'
  - '@takumi-rs/core-linux-x64-gnu@1.8.0'
  - '@takumi-rs/core-linux-x64-musl@1.8.0'
  - '@takumi-rs/core-win32-arm64-msvc@1.8.0'
  - '@takumi-rs/core-win32-x64-msvc@1.8.0'
  - '@takumi-rs/core@1.8.0'
  - '@takumi-rs/helpers@1.8.0'
  - electron@42.4.0
  - nuxt-schema-org@6.1.1
  - '@nuxtjs/seo@5.2.1'
  - '@takumi-rs/core-darwin-arm64@1.8.1'
  - '@takumi-rs/core-darwin-x64@1.8.1'
  - '@takumi-rs/core-linux-arm64-gnu@1.8.1'
  - '@takumi-rs/core-linux-arm64-musl@1.8.1'
  - '@takumi-rs/core-linux-x64-gnu@1.8.1'
  - '@takumi-rs/core-linux-x64-musl@1.8.1'
  - '@takumi-rs/core-win32-arm64-msvc@1.8.1'
  - '@takumi-rs/core-win32-x64-msvc@1.8.1'
  - '@takumi-rs/core@1.8.1'
  - '@takumi-rs/helpers@1.8.1'
  - nodemailer@8.0.11
  - nuxtseo-shared@5.2.1

overrides:
  nuxt-schema-org: 6.0.4
  "@nuxtjs/seo": 5.1.2
  "@intlify/shared": 11.4.2
  nitropack: 2.x.x
  nuxi: 3.x.x
  vue: 3.5.39
  vue-router: 5.1.0
  nuxt: 4.4.6

patchedDependencies:
  '@capacitor-community/app-icon': patches/@capacitor-community__app-icon.patch
