// // This file was generated by Prisma and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
import { defineConfig, env } from 'prisma/config'
import 'dotenv/config'

export default defineConfig({
  schema: "./server/prisma/schema.prisma",
  migrations: {
    path: "./server/prisma/migrations",
    seed: "tsx ./server/prisma/seed.ts",
    // seed: "bun run ./server/prisma/seed.ts",
  },
  datasource: {
    url: env("PSQL_URL"),
  },
});

