<template>
  <div class="privacy-policy">
    <h1>Privacy Policy</h1>
    <p class="last-updated">Last updated: May 10, 2026</p>

    <section>
      <h2>1. Introduction</h2>
      <p>
        At Bader Idris Portfolio ("we," "us," or "our"), we are committed to
        protecting your privacy. This Privacy Policy explains how we collect,
        use, disclose, and safeguard your information when you use our website,
        services, or digital goods, including full-stack development projects,
        online courses, blogs, and other applications (collectively, the
        "Services"). By using our Services, you consent to the practices
        described in this policy.
      </p>
    </section>

    <section>
      <h2>2. Information We Collect</h2>
      <p>
        As a full-stack developer, we collect data commonly required to operate
        and enhance our Services, consistent with industry-standard practices
        for web and mobile applications, APIs, and digital products. The types
        of information we may collect include:
      </p>
      <h3>2.1 Personal Data</h3>
      <p>
        We may collect personally identifiable information that you voluntarily
        provide, such as:
      </p>
      <ul>
        <li>Name and contact details (e.g., email address, phone number)</li>
        <li>
          Billing information (e.g., payment method details, billing address)
        </li>
        <li>Account credentials (e.g., username, password)</li>
        <li>
          Project-related information (e.g., specifications, feedback, or
          content provided for custom development)
        </li>
      </ul>
      <h3>2.2 Usage Data</h3>
      <p>
        We automatically collect data generated by your interaction with our
        Services, including:
      </p>
      <ul>
        <li>
          Device information (e.g., IP address, browser type, operating system)
        </li>
        <li>
          Usage patterns (e.g., pages visited, time spent, clicks, and
          navigation paths)
        </li>
        <li>Analytics data (e.g., session duration, feature usage)</li>
      </ul>
      <h3>2.3 Cookies and Tracking Technologies</h3>
      <p>
        We use cookies, web beacons, and similar technologies to enhance your
        experience and analyze usage. These may include:
      </p>
      <ul>
        <li>
          <strong>Necessary Cookies:</strong> Enable core functionality, such as
          authentication and session management.
        </li>
        <li>
          <strong>Functionality Cookies:</strong> Remember your preferences
          (e.g., language settings).
        </li>
        <li>
          <strong>Analytics Cookies:</strong> Track usage trends to improve our
          Services.
        </li>
      </ul>
      <p>
        You can manage cookie preferences through your browser settings, but
        disabling cookies may affect Service functionality.
      </p>
      <h3>2.4 Data from Authentication Services</h3>
      <p>
        If you log in using third-party authentication services (e.g., OAuth
        providers), we may collect limited data, such as your name or email
        address, as permitted by your settings with those services.
      </p>
    </section>

    <section>
      <h2>3. How We Use Your Information</h2>
      <p>
        We use your information to provide, maintain, and improve our Services,
        including:
      </p>
      <ul>
        <li>
          Delivering custom development projects, digital goods, and online
          courses.
        </li>
        <li>Processing payments and fulfilling orders.</li>
        <li>Authenticating users and securing accounts.</li>
        <li>
          Communicating with you about your account, projects, or updates.
        </li>
        <li>Analyzing usage to optimize performance and user experience.</li>
        <li>
          Marketing our Services, with your consent where required (e.g.,
          newsletters).
        </li>
        <li>Complying with legal obligations or resolving disputes.</li>
      </ul>
    </section>

    <section>
      <h2>4. Sharing Your Information</h2>
      <p>We may share your information in the following circumstances:</p>
      <ul>
        <li>
          <strong>With Service Providers:</strong> We use trusted third-party
          providers (e.g., payment processors like PayPal or Stripe, hosting
          services) to facilitate our Services. These providers are bound by
          confidentiality agreements.
        </li>
        <li>
          <strong>For Legal Purposes:</strong> We may disclose data to comply
          with legal obligations, respond to government requests, or protect our
          rights, users, or the public.
        </li>
        <li>
          <strong>In Business Transfers:</strong> If we undergo a merger,
          acquisition, or asset sale, your data may be transferred, with notice
          provided where feasible.
        </li>
        <li>
          <strong>With Your Consent:</strong> We may share data for other
          purposes if you explicitly agree.
        </li>
      </ul>
      <p>We do not sell your personal information to third parties.</p>
    </section>

    <section>
      <h2>5. Data Retention</h2>
      <p>
        We retain your personal data only as long as necessary for the purposes
        outlined in this policy, including fulfilling contracts, maintaining
        accounts, or meeting legal requirements. Usage data may be retained for
        analytics purposes, typically for a shorter period, unless required for
        security or compliance.
      </p>
    </section>

    <section>
      <h2>6. Data Transfers</h2>
      <p>
        Your data may be processed or stored in locations outside your country,
        including regions with different data protection laws. We implement
        safeguards (e.g., standard contractual clauses) to ensure your data is
        protected during transfers.
      </p>
    </section>

    <section>
      <h2>7. Your Privacy Rights</h2>
      <p>Depending on your jurisdiction, you may have rights to:</p>
      <ul>
        <li>Access or receive a copy of your personal data.</li>
        <li>Correct inaccurate or incomplete data.</li>
        <li>Request deletion of your data, subject to legal obligations.</li>
        <li>Opt out of marketing communications.</li>
        <li>Restrict or object to certain data processing activities.</li>
      </ul>
      <p>
        To exercise these rights, contact us using the details below. We may
        verify your identity before processing requests.
      </p>
    </section>

    <section>
      <h2>8. Data Security</h2>
      <p>
        We use industry-standard measures (e.g., encryption, access controls) to
        protect your data. However, no method of transmission or storage is
        completely secure, and we cannot guarantee absolute security.
      </p>
    </section>

    <section>
      <h2>9. Children's Privacy</h2>
      <p>
        Our Services are not intended for individuals under 13. We do not
        knowingly collect personal data from children under 13. If we learn such
        data has been collected, we will take steps to delete it. Parents or
        guardians may contact us if they believe their child has provided data.
      </p>
    </section>

    <section>
      <h2>10. Links to Other Websites</h2>
      <p>
        Our Services may link to third-party websites. We are not responsible
        for their privacy practices and encourage you to review their policies.
      </p>
    </section>

    <section>
      <h2>11. Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy to reflect changes in our practices or
        legal requirements. We will notify you via email or a notice on our
        website before significant changes take effect. Changes are effective
        upon posting.
      </p>
    </section>

    <section>
      <h2>12. Contact Us</h2>
      <p>If you have questions about this Privacy Policy, please contact us:</p>
      <ul>
        <li>
          Email:
          <a href="mailto:contact@baderidris.com">contact@baderidris.com</a>
        </li>
        <li>
          Contact Page:
          <a href="https://baderidris.com/contact">baderidris.com/contact</a>
        </li>
        <li>Phone: +970595744368</li>
      </ul>
    </section>
  </div>
</template>

<script setup>
useSeoMeta({
  title: "Privacy Policy - Bader Idris Portfolio",
  description:
    "Learn how Bader Idris Portfolio collects, uses, and protects your data when using our full-stack development services, digital products, and online courses.",
});

if (import.meta.server) {
  useSchemaOrg([
    defineWebPage({
      name: "Privacy Policy - Bader Idris Portfolio",
      description: "Learn how Bader Idris Portfolio collects, uses, and protects your data.",
    }),
    defineWebSite({
      name: 'Bader Idris Portfolio',
      url: 'https://baderidris.com'
    })
  ]);
}
</script>

<style lang="scss" scoped>
.privacy-policy {
  background-color: white;
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: "Arial", sans-serif;
  color: #333;

  h1 {
    font-size: 2.5rem;
    font-weight: bold;
    color: #222;
    margin-bottom: 1rem;
  }

  .last-updated {
    color: #666;
    font-size: 1rem;
    margin-bottom: 2rem;
  }

  section {
    margin-bottom: 2rem;

    h2 {
      font-size: 1.75rem;
      font-weight: 600;
      color: #222;
      margin-bottom: 1rem;
    }

    h3 {
      font-size: 1.25rem;
      font-weight: 600;
      color: #333;
      margin-bottom: 0.75rem;
    }

    p {
      font-size: 1rem;
      line-height: 1.6;
      color: #444;
      margin-bottom: 1rem;
    }

    ul {
      list-style-type: disc;
      padding-left: 1.5rem;
      margin-bottom: 1rem;

      li {
        font-size: 1rem;
        line-height: 1.6;
        color: #444;
        margin-bottom: 0.5rem;
      }
    }

    a {
      color: #007bff;
      text-decoration: none;
      transition: color 0.2s;

      &:hover {
        color: #0056b3;
        text-decoration: underline;
      }
    }
  }
}
</style>